version: '3'

services:
  minecraft-server:
    build: .
    ports:
      - "25565:25565"
    volumes:
      - ./mods:/data/mods
    environment:
      EULA: "TRUE"
      MEMORY: "2G"
    restart: always
