version: '3.8'

services:
  minecraft:
    build: .
    container_name: minecraft-server
    environment:
      - EULA=true
      - SERVER_PORT=25565
      - LEVEL_NAME=world
      - MAX_PLAYERS=20
      - MOTD=A Minecraft Server
      - SPAWN_PROTECTION=16
      - WHITELIST=false
      - DIFFICULTY=2
    volumes:
      - ./server-data:/data
      - ./mods:/data/mods
    ports:
      - "25565:25565"
    restart: unless-stopped
